import time
from typing import Tuple
import torch
from prometheus_client import Counter, Gauge, Histogram, generate_latest, CONTENT_TYPE_LATEST

# prometheus telemetry definitions
TTFT_HISTOGRAM = Histogram(
    "optiserve_ttft_seconds",
    "Time-to-first-token in seconds",
    buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5],
)

ITL_HISTOGRAM = Histogram(
    "optiserve_inter_token_latency_seconds",
    "Inter-token latency in seconds",
    buckets=[0.005, 0.01, 0.015, 0.02, 0.03, 0.05, 0.1, 0.2],
)

REQUESTS_COUNTER = Counter(
    "optiserve_requests_total",
    "Total requests served",
    ["mode", "status"],
)

TOKENS_COUNTER = Counter(
    "optiserve_tokens_generated_total",
    "Total tokens generated by the engine",
    ["mode"],
)

ACCEPTANCE_RATE_GAUGE = Gauge(
    "optiserve_speculative_acceptance_rate",
    "Empirical speculative acceptance rate alpha",
)

GPU_MEMORY_GAUGE = Gauge(
    "optiserve_gpu_memory_used_bytes",
    "Current GPU memory allocated in bytes",
)

ACTIVE_BATCH_GAUGE = Gauge(
    "optiserve_active_batch_size",
    "Number of requests currently in continuous batching queue",
)


def update_gpu_memory_metric():
    if torch.cuda.is_available():
        bytes_used = torch.cuda.memory_allocated()
        GPU_MEMORY_GAUGE.set(bytes_used)
    else:
        GPU_MEMORY_GAUGE.set(0)


def get_prometheus_metrics() -> Tuple[bytes, str]:
    update_gpu_memory_metric()
    return generate_latest(), CONTENT_TYPE_LATEST
